// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories.EFCore;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20240312200904_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            DepartmentName = "Yazılım Geliştirme"
                        },
                        new
                        {
                            DepartmentId = 2,
                            DepartmentName = "Test ve Kalite Güvence"
                        },
                        new
                        {
                            DepartmentId = 3,
                            DepartmentName = "Proje Yönetimi"
                        },
                        new
                        {
                            DepartmentId = 4,
                            DepartmentName = "Ürün Yönetimi"
                        },
                        new
                        {
                            DepartmentId = 5,
                            DepartmentName = "Satış ve Pazarlama"
                        },
                        new
                        {
                            DepartmentId = 6,
                            DepartmentName = "İnsan Kaynakları"
                        },
                        new
                        {
                            DepartmentId = 7,
                            DepartmentName = "Finans ve Muhasebe"
                        },
                        new
                        {
                            DepartmentId = 8,
                            DepartmentName = "Bilgi Teknolojileri (BT)"
                        });
                });

            modelBuilder.Entity("Entities.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 3, 12, 23, 9, 4, 35, DateTimeKind.Local).AddTicks(8507),
                            Description = "Description",
                            LastUpdate = new DateTime(2024, 3, 12, 23, 9, 4, 35, DateTimeKind.Local).AddTicks(8524),
                            Price = 100m,
                            Title = "Product 1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 3, 12, 23, 9, 4, 35, DateTimeKind.Local).AddTicks(8525),
                            Description = "Description",
                            LastUpdate = new DateTime(2024, 3, 12, 23, 9, 4, 35, DateTimeKind.Local).AddTicks(8526),
                            Price = 75m,
                            Title = "Product 2"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 3, 12, 23, 9, 4, 35, DateTimeKind.Local).AddTicks(8527),
                            Description = "Description",
                            LastUpdate = new DateTime(2024, 3, 12, 23, 9, 4, 35, DateTimeKind.Local).AddTicks(8528),
                            Price = 200m,
                            Title = "Product 3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
