// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories.EFCore;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20240307132805_startPoint")]
    partial class startPoint
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 3, 7, 16, 28, 5, 344, DateTimeKind.Local).AddTicks(6602),
                            Description = "Description",
                            LastUpdate = new DateTime(2024, 3, 7, 16, 28, 5, 344, DateTimeKind.Local).AddTicks(6614),
                            Price = 100m,
                            Title = "Product 1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 3, 7, 16, 28, 5, 344, DateTimeKind.Local).AddTicks(6615),
                            Description = "Description",
                            LastUpdate = new DateTime(2024, 3, 7, 16, 28, 5, 344, DateTimeKind.Local).AddTicks(6616),
                            Price = 75m,
                            Title = "Product 2"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 3, 7, 16, 28, 5, 344, DateTimeKind.Local).AddTicks(6617),
                            Description = "Description",
                            LastUpdate = new DateTime(2024, 3, 7, 16, 28, 5, 344, DateTimeKind.Local).AddTicks(6617),
                            Price = 200m,
                            Title = "Product 3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
